-- Migration: Add Trading Agents Tables
-- Created: 2025-12-29
-- Description: Creates tables for trading agents and their signals

-- Table: trading_agents
-- Stores agent definitions and configurations
CREATE TABLE IF NOT EXISTS trading_agents (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('PULLBACK', 'BREAKOUT', 'MOMENTUM', 'REVERSAL')),
  enabled BOOLEAN DEFAULT true,
  criteria JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Table: agent_signals
-- Stores signals generated by agents
CREATE TABLE IF NOT EXISTS agent_signals (
  id SERIAL PRIMARY KEY,
  agent_id INTEGER REFERENCES trading_agents(id) ON DELETE CASCADE,
  ticker TEXT NOT NULL,
  signal_date DATE NOT NULL,
  setup_data JSONB NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_agent_signals_date ON agent_signals(signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_agent_signals_ticker ON agent_signals(ticker);
CREATE INDEX IF NOT EXISTS idx_agent_signals_active ON agent_signals(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_agent_signals_agent_id ON agent_signals(agent_id);

-- Insert default Trend + Pullback agent
INSERT INTO trading_agents (name, type, enabled, criteria)
VALUES (
  'Trend + Pullback',
  'PULLBACK',
  true,
  '{
    "closeAboveSMA200": true,
    "sma50AboveSMA200": true,
    "pullbackDays": {"min": 2, "max": 6},
    "pullbackTarget": "EMA20",
    "minRelativeVolume": 0.5,
    "rsi": {"min": 30, "max": 50}
  }'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert default Breakout agent
INSERT INTO trading_agents (name, type, enabled, criteria)
VALUES (
  'Breakout',
  'BREAKOUT',
  true,
  '{
    "consolidationDays": {"min": 10, "max": 30},
    "rangeMultiplier": 2.0,
    "volumeMultiplier": 1.5,
    "atrExpanding": true
  }'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert default Strong Momentum agent
INSERT INTO trading_agents (name, type, enabled, criteria)
VALUES (
  'Strong Momentum',
  'MOMENTUM',
  true,
  '{
    "emaAlignment": true,
    "ema20SlopeMin": 0.05,
    "rsi": {"min": 60, "max": 75},
    "volumeAboveAverage": true
  }'::jsonb
)
ON CONFLICT DO NOTHING;

-- Insert default Reversal agent
INSERT INTO trading_agents (name, type, enabled, criteria)
VALUES (
  'Reversal',
  'REVERSAL',
  true,
  '{
    "rsiMax": 30,
    "closeAboveEMA20": true,
    "volumeMultiplier": 1.5,
    "bullishCandle": true
  }'::jsonb
)
ON CONFLICT DO NOTHING;

COMMENT ON TABLE trading_agents IS 'Trading agent definitions with criteria';
COMMENT ON TABLE agent_signals IS 'Signals generated by trading agents';
COMMENT ON COLUMN agent_signals.setup_data IS 'JSON data containing signal details (entry, stop, strength, etc)';
